### PR TITLE
Issue buttons visual improvements

### PR DESCRIPTION
**Pull request by davidread**
* Edit button colours improved.
* Abuse button made much more subtle and tooltips now work.

### CODE REVIEW

**Comment by davidread** [comment]
Test is now fixed

**Comment by davidread** [comment]
I'm not quite sure whether this is what's needed. I've gone for the model I envisage happening in https://github.com/okfn/ckanext-issues/issues/27 however that's not the current aim. I'm not really clear how your issue.spam_count and issue.spam_state are supposed to work. Perhaps we can chat about this?

**Comment by davidread** [comment]
I do want to keep the subtlness of the edit and report buttons in the PR. But I don't think the model supports the report button being a toggle, as it is not saved who reported it, so if you refresh the page then you shouldn't be able to see whether you reported it as spam or not - (or maybe you're going to store it in the session?). In which case, maybe just seeing the flash message is enough. Maybe it would be easier to just store who reported it...

**Comment by davidread** [comment]
@joetsoi can you decide how to progress this PR please?

**Comment by joetsoi** [comment]
merging for now,  I agree on storing the users would be better. I did think about have a json serialized list of names instead of a spam count. That would be the next better step forwards

**Pull request merged**
